### PR TITLE
Update version to 0.1.2

### PR DESCRIPTION
**Pull request by luca-s**
@twiecki time for a new version? Or too early?

### CODE REVIEW

**Comment by twiecki** [comment]
Never too early.

**Comment by luca-s** [comment]
I created a tag for the release

**Comment by twiecki** [comment]
Can you add some brief release-notes to https://github.com/quantopian/alphalens/releases/tag/v0.1.2?

**Comment by luca-s** [comment]
Sure, done.

**Comment by twiecki** [comment]
Appreciate it!

**Comment by luca-s** [comment]
@twiecki I just realized that Alphalens documentation says to install it via 'pip install git+https://github.com/quantopian/alphalens' but pypi has an old version of Alphalens too (v0.1.0). I think we should either update Alphalens release on pypi or remove that from pypi. What do you think?

Also, quantopian.github.io/alphalens still has the old v0.1.1 version.

**Comment by twiecki** [comment]
Good catch, I just pushed a new version to pypi.

**Comment by twiecki** [comment]
Also updated the docs. I think we should change the install instructions to `pip install alphalens` though.

**Comment by luca-s** [comment]
Fine with me

**Pull request merged**
