### PR TITLE
Updated functions documentation: related to #187

### PR DESCRIPTION
**Pull request by luca-s**
Explained how to interpret the cumulative return for N forward period in
performace.plot_cumulative_returns and performance.plot_cumulative_returns_by_quantile

### CODE REVIEW

**Comment by luca-s** [comment]
@twiecki Could you please double check the explanation I added is clear?

**Comment by HereticSK** [comment]
If we are to mimic the cumulative return for the algorithm that holding N equal weighted sub-portfolios and rebalancing them every N period, I wonder if it would make more sense to compute the one-period return as `np.nanmean((1 + ret) ** (1. / period) - 1)`? 

Compared to the original algorithm, it computes geometric mean before arithmetic mean. For a given period, the one-period return for the whole portfolio equals the average of one-period returns for N sub-portfolios. On the other hand, assuming each sub-portfolio grows at a steady rate within each rebalancing cycle, the one-period return for each sub-portfolio is given by the geometric mean of the corresponding N-period return, i.e. `(1 + ret)**(1. / period) - 1)`. Combining these two steps, gives the one-period return of the whole portfolio equals `np.nanmean((1 + ret) ** (1. / period) - 1)`.

Moreover, in the original algorithm, `((np.nanmean(ret) + 1) ** (1. / period)) - 1`, the N-period returns for each sub-portfolio is averaged first. Somehow that seems like all these N-period returns are realized at this particular period, while they are actually realized at subsequent N periods. So I think it would make more sense to first compute (1 + ret) ** (1. / period) - 1), as an estimation of the realized return for a sub-portfolio on the given period, and then to average over all the sub-portfolios.

**Comment by luca-s** [comment]
@HereticSK as this is a PR that only involves documenting the current functions behaviour, would you mind removing you last comment and copy paste it on the #187 issue? That would be much neat as we can keep discussing possible improvements on #187 issue, while this PR could be merged in the meanwhile as it only documents the behaviors that is already in the code

**Comment by luca-s** [comment]
Closing this, I will provide another PR

**Pull request closed without merging**
