### PR TITLE
Better error message for not enough quantiles for factor values

### PR DESCRIPTION
**Pull request by luca-s**
Fix issue #152

### CODE REVIEW

**Comment by twiecki** [comment]
Why the use of a decorator if it's just in a single function?

**Comment by luca-s** [comment]
The other option would have been to wrap the whole function body around a try/catch, plus the endless message. I thought that would have made the function hard to read and ugly.

**Comment by twiecki** [comment]
I see, I think this looks good!

**Comment by twiecki** [comment]
We should cut a new release.

**Pull request merged**
