### PR TITLE
tweaks from API recommendations

### PR DESCRIPTION
**Pull request by jameschristopher**

### CODE REVIEW

**Comment by twiecki** [comment]
Why did so many indents change? PEP8 recommends 80 char limit. I personally think there are good cases not to do that, but some of changes here revert something that was broken up elegantly.

**Comment by jameschristopher** [comment]
indentation changes are an artifact of my editor, the default was incorrectly set. can fix that easily.

**Comment by twiecki** [comment]
OK, lets revert those to also make it easier to review.

**Comment by jameschristopher** [comment]
what indentation convention do we want to use when defining function?

https://github.com/quantopian/pyfolio/blob/master/pyfolio/plotting.py#L573-L575

or 

https://github.com/quantopian/pyfolio/blob/master/pyfolio/plotting.py#L502-L503

what indentation convention do we want to use for calling functions? there is this kind in pyfolio:

https://github.com/quantopian/pyfolio/blob/master/pyfolio/plotting.py#L360-L365

and then there is this kind also in pyfolio

https://github.com/quantopian/pyfolio/blob/master/pyfolio/plotting.py#L418-L422

**Comment by twiecki** [comment]
> I'm a big fan of aligning with the left parenthese and only having one argument per line.

That's fine with me.

**Comment by twiecki** [comment]
LGTM.

**Pull request merged**
