### PR TITLE
Update IC Risk Adjusted Ratio Calculation

### PR DESCRIPTION
**Pull request by MichaelJMath**
In response to issue #208 , this modifies and renames risk-adjusted IC calculation. I also moved this "Risk-Adjusted IC" to immediately follow the "IC Mean" and "IC Std." fields. This seems to be more logical especially since the "t-stat (IC)" field immediately follows, which I believe is simply the risk-adjusted IC times the square root of the number of periods.

### CODE REVIEW

**Comment by twiecki** [comment]
`alphalens/plotting.py:177:5: E303 too many blank lines (2)`

**Comment by twiecki** [comment]
@richafrank We realized that the "IR" we calculated was wrong, this fixes it and gives it a better name (see #208 for discussion).

**Comment by luca-s** [comment]
@MichaelJMath could you rebase your branch on top of current alphalens master?

```
git checkout master

# assuming you called upstream the official alphalens remote
git fetch upstream -p 

git rebase upstream/master

git checkout update_ic_risk_adjusted 
git rebase master

git push origin update_ic_risk_adjusted -f
```

**Comment by MichaelJMath** [comment]
I rebased by following your instructions. I had quite a few simple merge conflicts, although I ended up having to git rebase --skip for all of them as it wouldn't accept my changes. Let me know if that does the trick.

Was there a problem with the way I pulled in changes from upstream/master to my origin/master branch? (I'm just trying to learn for future reference.)

**Comment by luca-s** [comment]
@MichaelJMath some unwanted changes were left in alphalens/utils.py, could you remove those please?

I don't know what was the stare of your update_ic_risk_adjusted branch when you created the PR but github complained that it couldn't automatically merge your PR due to conflicts. So I just wanted to make sure your branch was updated with upstream/master.

In general I like to update my local master branch from upstream before creating a new branch.

```
git checkout master

# assuming you called upstream the official alphalens remote
git fetch upstream -p 

git rebase upstream/master

# probably you also want to update origin/master
git push origin master
```

Then I create a branch and I start to develop. If I forgot to update the master when I created the branch or if some new commits land on the upstream/master after the creation of the branch, I do the steps above plus:

```
git checkout my_branch 
git rebase master

# add -f is you had already pushed commits on origin
git push origin my_branch 
```

**Comment by MichaelJMath** [comment]
@luca-s I think my last commits should have fixed it. I'm not really sure what I did to create those duplicate functions in utils.py. I apologize for the hassle.

I typically try and sync my origin/master with upstream/master before creating a new branch (although I use git pull, which, as you know, by default merges instead of rebases). I may have forgotten to push the changes to my origin/master after pulling to my local master. 

Is it preferred to rebase instead of merge?

Thanks for all the help by the way.

**Comment by luca-s** [comment]
@MichaelJMath The beauty of git :) It's a good tool but sometimes you find yourself in weird scenarios. And don't apologize, it's good to have someone looking at the code and finding bugs. Thanks for your contribution.

I like rebasing instead of merging because the history appear linear afterward but I believe it is the same with a fast forward merge. It is a matter of personal preferences anyway, when the PR branch is merged to the main master we can choose how we want to do it, so what you do on your side is not too relevant.

**Comment by twiecki** [comment]
Thanks @MichaelJMath (and @luca-s for the review)!

**Pull request merged**
