### PR TITLE
WIP - new api

### PR DESCRIPTION
**Pull request by jameschristopher**
Here is where I'm headed with the new api thoughts from https://github.com/quantopian/alphalens/pull/110 so to review creating a tear sheet would be a two step process.

1. format the data
2. call for the tear sheet 

where all of the tear sheets take a `factor_data` dataframe that looks something like 
screen shot 2017-01-13 at 11 53 54 am

Right now the main blocking issue is the event-study-esque plots as that [function](https://github.com/quantopian/alphalens/blob/master/alphalens/performance.py#L469) requires raw prices. I think that the number of plots and the uniqueness of what they are saying probably merits them getting a separate tear sheet (which would be able to take raw prices).

### CODE REVIEW

**Comment by twiecki** [comment]
This looks like a great start. Did you start from recent master? Seems like there are conflicts.

**Comment by luca-s** [comment]
Your changes look good to me. I agree with you that the event-study-esque plots could go in a separate tear sheet. Still dropping `prices` after the initial data formatting process means we are losing information and it might become a problem for the development of future features. But this is just a minor issue and It might not be a problem at all, I just wanted to highlight this. 

A side note regarding the data, we are probably not following the tidy data guidelines you mentioned in #110 (thanks for the article, that was interesting). But we can fix it later on I guess, if we really want to do it.

**Comment by twiecki** [comment]
@luca-s Which part of tidy data are we missing? The fact that the forward returns periods should actually be a hierarchical index?

**Comment by luca-s** [comment]
My understanding is that the forward returns periods should not be columns headers but rather values in a  dedicated column. So we would have only two columns for the forward returns: a column whose values are the number of periods (1, 5, 10 or whatever) and another column with the forward return values for each periods.

**Comment by twiecki** [comment]
yes, except that your first column should also be an index, I think. Btw. now is the time to think about this.

**Comment by jameschristopher** [comment]
@twiecki I opened the branch last Friday so I think I'm about 5 commits behind. 

Luca I'm not so sure, the author defines a value as 

> Value: The actual measurement or attribute. 152 cm, 80 kg, female, etc.

The number of periods are not a measured attribute of the factor, they are part of the measurement process of forward returns. So I'd argue that they should be incorporated into the column header.

**Comment by luca-s** [comment]
@jameschristopher it seems to me the example of the 'Income" column really matches our use case. Also I believe the number of periods should be a column because I have already faced the problem of needing the number of periods as a parameter and I ended up reading it from the column name. That cannot be tidy data :) If you think about it, we don't have that information in our DataFrame expect for the column names. Maybe those are weak points but I just wanted to make them clear anyway so we can take the best decision.

**Comment by jameschristopher** [comment]
Those are weak points. That is an excellent point and something I've also thought about. A common issue that I ran into with this PR is getting the forward returns columns over and over again. You can see in the code that I use a regex to do this - not so elegant.

**Comment by twiecki** [comment]
I think it should definitely be an index-level (or column, but it's not really data, it's an identifier). Not separate columns as it is now.

**Comment by jameschristopher** [comment]
Thomas can you provide an illustration of what you mean? Something like this?
screen shot 2017-01-24 at 7 20 08 am

**Comment by twiecki** [comment]
@jameschristopher exactly like that.

**Comment by jameschristopher** [comment]
yes as would 'group' and 'quantile'

**Comment by jameschristopher** [comment]
After some more thought I'd like to submit a multilevel column as the approach we should take
screen shot 2017-02-02 at 4 11 43 pm

**Comment by twiecki** [comment]
I think that's the best solution so far. @luca-s do you agree?

**Comment by luca-s** [comment]
That's fine with me. We have already had the chance to discuss all the relevant points, so I certainly trust James choice if he thinks that's the best way to go. Let's go with that then.

**Comment by twiecki** [comment]
Did you remove the hierarchical column again? screen shot 2017-02-13 at 08 58 25

**Comment by twiecki** [comment]
But I think otherwise this looks great. @luca-s can you take a quick look too?

**Comment by luca-s** [comment]
Sure, I will.

**Comment by luca-s** [comment]
Great work, I like the new api. 

I only have few comments:

1 - 'quantile_factor.max()'  (used to fetch the number of quantiles/bins) should be replaced with 'int(quantile_factor.max())' because quantiles/bins values might be float, depending on quantiles/bins arguments and that would break the code.

2 - We don't have quantile statistics anymore. I found them very useful when using non default quantiles/bins arguments.

screenshot from 2017-02-13 12-15-45

3 - Could you please add the call to 'create_event_returns_tear_sheet' in the 'predictive_vs_non-predictive_factor' NB? As the purpose of that NB is to show what to expect in each plot in the cases of  predictive and non-predicvive fators it would be useful to have all the plots there.

4- I miss to have mean return and event style return plots side by side, but there is no much we can do about it.

screenshot from 2017-02-13 12-45-04

**Comment by luca-s** [comment]
I noticed another little issue at [here](https://github.com/quantopian/alphalens/blob/new-api/alphalens/utils.py#L306). When calling `util.quantize_factor` it is possible that some of the factor values are dropped, depending on the quantiles/bins arguments. This is a feature, as it could be useful to drop top/bottom values as a measure to remove outliers. So we don't want to keep factor entries whose values are NaN, this means a second call to 
`merged_data = merged_data.dropna()` is required after calling `util.quantize_factor`

**Comment by jameschristopher** [comment]
Yes Thomas the hierarchical columns weren't workable.

If there are no further comments I'd like to merge this PR, wait a week to see what bugs come up, fix those bugs and push an official release `v0.1` to PyPi.

**Comment by twiecki** [comment]
This was not an easy one -- thanks @jameschristopher and @luca-s!

**Comment by luca-s** [comment]
thanks @jameschristopher

**Pull request merged**
