### PR TITLE
Addressing issue #336

### PR DESCRIPTION
**Pull request by jimportico**
Added code to address issue #336. 

link: https://github.com/quantopian/alphalens/issues/336

### CODE REVIEW

**Comment by twiecki** [comment]
@jimportico Looks great, thanks for contributing this! Seems like our travis CI is broken, did you run the test suite to make things everything still passes?

**Comment by jimportico** [comment]
Hi @twiecki - I checked travis CI and see four failure messages that I'm having a difficulty reconciling. 

Build Jobs:
* 630.1:  The command "python setup.py install" failed and exited with 1 during .
* 630.2, 630.4, & 630.5:  The command "conda create -q -n testenv --yes python=$TRAVIS_PYTHON_VERSION ipython flake8 numpy scipy nose matplotlib pandas=$PANDAS_VERSION statsmodels seaborn" failed and exited with 1 during .

I saw something similar on PR #346. That looked unrelated to the changes being submitted. Is that the case for mine as well?

**Comment by twiecki** [comment]
Yeah those are unrelated, just wanted to make sure they did pass with a
functioning setup.

**Comment by twiecki** [comment]
Thanks @jimportico!

**Comment by twiecki** [comment]
If you want, in a separate PR you could add a unittest to make sure the feature works as desired.

**Comment by jimportico** [comment]
Thanks @twiecki - happy to help! I haven't submitted a unittest for an OSS project before but would like to learn more. Do you have a sample you can point me toward?

**Pull request merged**
