### PR TITLE
Keep most recent data

### PR DESCRIPTION
**Pull request by jzhang18**
Modified the way to drop nan values for `merged_data`. By this way, it only drops the data that does not have valid `factor value` or `factor_quantile`.

### CODE REVIEW

**Comment by luca-s** [comment]
Seems good to me. Just to be sure, Do you need this to avoid dropping data when you have some forward return columns contain valid data but few of them have nan?

**Comment by jzhang18** [comment]
@luca-s yes, that's the reason.

**Comment by luca-s** [comment]
Ok then but I would also add another dropna that discards all the rows for which we have nan in **all** the forward return columns. This would make clear the user didn't pass data for a particular time period. What do you think about this?

**Comment by twiecki** [comment]
After talking about it with @jzhang18 we don't think this should be fixed in alphalens.

**Pull request closed without merging**
