### PR TITLE
ENH Speed up fwdret computation

### PR DESCRIPTION
**Pull request by twiecki**
By computing directly from prices rather than using `pct_change()`.

### CODE REVIEW

**Comment by twiecki** [comment]
Seeing a 4x increase in speed.

**Comment by luca-s** [comment]
Have you tried multiple version of pandas?

**Comment by twiecki** [comment]
Travis covers those.

**Comment by luca-s** [comment]
I meant if you noticed a speed improvements on multiple pandas version or just one specific version (Quantopian's version I suppose)

**Comment by twiecki** [comment]
I see, I haven't tested that, but I'd be surprised if there were big differences between versions there.

**Pull request merged**
