### PR TITLE
PEP8

### LINKED ISSUE #178: PEP8
Currently, alphalens does not follow pep8 guidelines. Quantopian enforces pep8 on all other codebases, so alphalens ought to do the same. This will make alphalens much easier to read for anyone interested in using it as open source software.

I'll open a PR for this.

### PR DESCRIPTION
**Pull request by georgh0021**
Fixes #178

### CODE REVIEW

**Comment by twiecki** [comment]
Did you run autopep8?

**Comment by georgh0021** [comment]
I did not know there was such a package!! I was just thinking to myself "gee, there should be something out there for this stuff"...

**Comment by georgh0021** [comment]
Looks like the tests don't follow pep8 either. Will fix that now.

**Comment by georgh0021** [comment]
Why does Travis kick off two builds every time we push to the branch? One for the PR, and one for the most recent push... Isn't that redundant? How can we change that?

Other than that, all tests passed and PR is ready for review @twiecki 

Also, nice to 'meet' you @luca-s! My name is George, and I'll be working on `alphalens` a bit over the next few weeks. Here's to creating enterprise value!

**Comment by richafrank** [comment]
> Why does Travis kick off two builds every time we push to the branch? One for the PR, and one for the most recent push... Isn't that redundant? How can we change that?

There are two options in the Travis settings for the repo: "Build branch updates" and "Build pull request updates". You can disable building branch updates to remove the duplicates. 

For zipline, we wanted to remove the duplicates but also test master when there's been a merge or commits made, so we used a different method: we specify in the [travis config](https://github.com/quantopian/zipline/blob/0a481d4d6caf1bb185e68826cb8c4ac155c03069/.travis.yml#L80-L82) to filter down the branches built to only master.

**Pull request merged**
